// react-js/src/Components/ListTodo.jsx
import React, { useState } from "react";
import { AiFillEdit, AiOutlineCloseCircle } from "react-icons/ai";
import { useDispatch, useSelector } from "react-redux";
import { deleteToDo, editTodo } from "../Reducers/toDoSlider";

const ListTodo = () => {
  const { todoList } = useSelector((state) => state.toDo);
  const dispatch = useDispatch();
  const [isEditing, setEditing] = useState(false);
  const [state, setState] = useState({
    id: "",
    content: "",
    contentError: null,
  });

  const onEditToggle = (id, content) => {
    setEditing(true);
    setState({
      ...state,
      id,
      content,
    });
  };

  const handleChange = (e) => {
    setState({
      ...state,
      [e.target.name]: e.target.value,
      [`${e.target.name}Error`]: null,
    });
  };

  const { content, contentError, id } = state;

  const edit = () => {
    if (content === "") {
      setState({ ...state, contentError: "You must write something!" });
      return;
    }
    dispatch(editTodo({ content, id }));
    setEditing(false);
  };

  return (
    <div>
      {isEditing ? (
        <div className="form">
          <h2>Update your plan for today</h2>
          <input
            type="text"
            value={content}
            name="content"
            onChange={handleChange}
          ></input>
          <button type="button" className="button" onClick={edit}>
            Edit
          </button>
          {contentError ? <div className="error">{contentError}</div> : null}
        </div>
      ) : (
        <ul className="todos">
          {todoList.map(({ id, content }) => {
            return (
              <li className="grid" key={id}>
                <span className="content">{content}</span>
                <span className="todo-action">
                  <AiOutlineCloseCircle
                    className="close"
                    onClick={() => dispatch(deleteToDo({ id }))}
                  />
                  <AiFillEdit
                    className="edit"
                    onClick={() => onEditToggle(id, content)}
                  />
                </span>
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
};

export default ListTodo;

// vue/src/components/ListTodo.vue
<template>
   <div>
    <template v-if="isEditing">
      <div class="form">
        <h2>Update your plan for today</h2>
        <input type="text" v-model="content" @input="clearError"/>
        <button type="button" class="button" @click="edit">Edit</button>
        <div v-if="contentError" class="error">{{ contentError }}</div>
      </div>
    </template>
    <template v-else>
      <ul class="todos">
        <li class="grid" v-for="todo in todoList" :key="todo.id">
          <span class="content">{{ todo.content }}</span>
          <span class="todo-action">
			<button class="close" @click="deleteItem(todo.id)">
				❌	
			</button>
			<button class="edit" @click="onEditToggle(todo.id, todo.content)">
				🖋️ 
			</button>

            <!-- <AiOutlineCloseCircle class="close" @click="deleteItem(todo.id)" /> -->
            <!-- <AiFillEdit class="edit" @click="onEditToggle(todo.id, todo.content)" /> -->
          </span>
        </li>
      </ul>
    </template>
  </div>
</template>

<script>
import { ref, watch } from 'vue';
import { useTodoStore } from '../stores/todo';
export default {
	name: "ListTodo",
  
  setup() {
    const store = useTodoStore();
    const todoList = ref(store.todoList);
    const isEditing = ref(false);
    const content = ref("");
    const contentError = ref(null);
    const todoId = ref("");

	watch(
      () => store.todoList,
      (newTodoList) => {
        todoList.value = newTodoList;
      }
    );

    const clearError = () => {
      contentError.value = null;
    };

    const onEditToggle = (id, todoContent) => {
		console.log('id, content: ', id, todoContent);
      isEditing.value = true;
      todoId.value = id;
      content.value = todoContent;
    };

    const handleChange = (e) => {
      content.value = e.target.value;
      contentError.value = null;
    };

    const edit = () => {
      if (!content.value.trim()) {
        contentError.value = "You must write something!";
        return;
      }
	  store.editTodo(todoId.value,{ content: content.value, id: todoId.value })
      isEditing.value = false;
    };

    const deleteItem = (id) => {
		store.deleteToDo(id)
    };

    return {
      todoList,
      isEditing,
      content,
      contentError,
      clearError,
      onEditToggle,
      handleChange,
      edit,
      deleteItem,
    };
  },
}
</script>
