// vue/src/components/AddTodo.vue
<template>
   <div className="form">
      <h2>What's your plan for today</h2>
      <input
		v-model="content"
        value="content"
        name="content"
      />
      <button type="button" class="button" @click="add">
        Add
      </button>
	  
	  <div v-if="contentError" class="error">{{ contentError }}</div>
	  
    </div>
</template>

<script setup lang="ts">
import {  ref } from "vue";
import { useTodoStore } from "../stores/todo";


    const store = useTodoStore();
    const content = ref("");
    const contentError = ref<string|null>(null);

    const clearError = () => {
      contentError.value = null;
    };

    const add = () => {
      if (!content.value.trim()) {
        contentError.value = "You must write something!";
        return;
      }

      store.addTodo(content.value);
      content.value = "";
	  clearError();
    };
</script>

// react-js/src/Components/AddTodo.jsx
import React, { useState } from "react";
import { useDispatch } from "react-redux";
import { addToDo } from "../Reducers/toDoSlider";

const AddTodo = () => {
  const dispatch = useDispatch();
  const [state, setState] = useState({
    content: "",
    contentError: null,
  });

  const handleChange = (e) => {
    setState({
      ...state,
      [e.target.name]: e.target.value,
      [`${e.target.name}Error`]: null,
    });
  };

  const add = () => {
    if (content === "") {
      setState({ ...state, contentError: "You must write something!" });
      return;
    }

    dispatch(addToDo({ newContent: content }));
    setState({ ...state, content: "" });
  };
  const { content, contentError } = state;
  return (
    <div className="form">
      <h2>What's your plan for today</h2>
      <input
        type="text"
        value={content}
        name="content"
        onChange={handleChange}
      ></input>
      <button type="button" className="button" onClick={add}>
        Add
      </button>
      {contentError ? <div className="error">{contentError}</div> : null}
    </div>
  );
};

export default AddTodo;
